### ISSUE TITLE
Folder naming by rating does not work on Gelbooru

### ISSUE THREAD

**Issue by purplenya** [kuanyui/BooruShinshi#3]
I've been fiddling around with the settings and I really like being able to sort automatically by the tags. However, I tried filtering by rating (like rating:explicit or rating:general), but it seems to just go to the fallback on entries with them. I have yet to try this with any other sources than gelbooru though.

**Comment by kuanyui** [comment]
Don't sure what you are talking about. It would be better to provide some screenshots when reporting issue.

But if you are meaning the rate of safe/questionable/explicit, yes I doesn't implement this feature at all.

**Comment by purplenya** [comment]
Sorry, didn't think to include screenshots. But yes, I was referencing the rating of the image. 
I figure it would be handy to be able to have a setup like this, just to add an extra layer of separation between them. 
![image](https://user-images.githubusercontent.com/122074925/210938951-6f4e34e3-def7-4aba-a0a4-3a7f3b734879.png)

**Comment by kuanyui** [comment]
`rating:explicit` is NOT belonged to tags and won't be handled by this WebExtension, so they are surely not used to filter files.
![Screenshot_20230106_140133_Firefox Focus](https://user-images.githubusercontent.com/1370070/210940393-0bd43bed-7829-41ce-857f-85ec220cb925.jpg)

**Comment by purplenya** [comment]
As the Statistics area is still in the element that includes the tags, I will attempt to add the functionality. If I do, I will open a pull request for it.
![image](https://user-images.githubusercontent.com/122074925/210942576-e9fe024f-72de-4f3a-906c-c7d852b6a345.png)
