### ISSUE TITLE
Downloads failing on danbooru

### ISSUE THREAD

**Issue by K400b** [kuanyui/BooruShinshi#7]
When clicking the extension download button for the high quality image it always fails the first time. At times the second click will download the image. At other times I have to reload the page and then click download twice for the download of the image to succeed.

Firefox only says "Failed" as reason next to the downloads and does not give any other error.

Also tried on a different Firefox profile. Firefox version is 126.0.1 64bit on Windows 11. Extension version is 0.10.13.
Also tried without any other extensions running.

The extension works fine on 2 other boorus I tried out, it is just danbooru it fails.

**Comment by kuanyui** [comment]
Yes I also noticed this issue months ago but don't have time to fix. Please
feel free to fix it if you are urgently need this.

2024年6月3日(月) 16:34 K400b ***@***.***>:
