### ISSUE TITLE
Past around 500 tags the Tag Block List will not save

### ISSUE THREAD

**Issue by Azriel-Satan** [kuanyui/BooruShinshi#8]
- Changes to the Block List textbox are not saved if more than 500 tags are inputted.
- This limitation is present when using both newlines and spaces.
- 500 is not an exact limit, but it functions there and not at 600.

I am an unusual case as I maintain a very long list of artists I have Blocked (currently standing at 1874 artists totaling 2036 tags) and use the Block List function to exclude followed artists when looking for new ones (totaling 2856 tags). In attempting to use to tag blacklist from Booru Sushi to get around sites that do not have functional Block Lists (Rule34) or have aggressive Cloudflare settings (Gelbooru), I discovered that somewhere past the 500 mark, it would not save inputs made to the blocklist.

**Comment by kuanyui** [comment]
I have never set any length nor amount limit on block list, so don't sure
why you encounter this problem...

Can you provide your setting file for debugging? (press "Export as JSON" in
BooruShinshi's setting page)

2024年7月18日(木) 13:30 Azriel-Satan ***@***.***>:

**Comment by Azriel-Satan** [comment]
[BooruShinshiSettings_20240719_040059.json](https://github.com/user-attachments/files/16309156/BooruShinshiSettings_20240719_040059.json)

**Comment by kuanyui** [comment]
I've tried your setting file, but cannot reproduce the issue you've
described.

I entered random tags after your tags, and it still can save without any
problem.

1. Consider backing up your settings JSON file and reinstalling Booru
Shinshi?
2. Are you sure your Firefox is update-to-date? (My platform: Firefox 127)
3. Have you ever try to create a new clean Firefox profile (startup Firefox
via `firefox -P`), and try to reproduce it with your settings JSON file?

2024年7月19日(金) 16:06 Azriel-Satan ***@***.***>:

**Comment by kuanyui** [comment]
No more response, no more information, close as invalid issue.

**Comment by Azriel-Satan** [comment]
I run Librewolf as my Main.
Installed a Fresh instance of Firefox Version 129.0.2 and pasted my block list; despite the Settings Saved popup, it returns to the previous state when the tab is reloaded.
Testing it, I was able to save up to 566 tags, but further attempts saw that I was able to save part of the next tag; the most I could get it to store was 5759 characters; past that point, no changes are kept.
[BooruShinshiSettings_20240826_225113.json](https://github.com/user-attachments/files/16755862/BooruShinshiSettings_20240826_225113.json)

**Comment by kuanyui** [comment]
OK found where the problem is. It's `browser.storage.sync` has quota limit. Your setting is too large so out of quota. From BooruShinshi 0.12.0, it always use `browser.storage.local` to save settings. However this means the BooruShinshi's settings will no longer be backed-up & synchronized by Mozilla Account.  

**Don't` ask me to add an option to let user switch between sync/local, it's too troublesome. Please backup your settings by yourself.**

https://github.com/kuanyui/BooruShinshi/commit/5c356535966ad471be9ec29f46ca70290774a716
